name: dickerhub

on:
    release:
        types:
            - published

jobs:
    push_to_dockerhub:
        name: Push image to dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: |
                   ffffuuu/aklapi:latest
                   ffffuuu/aklapi:${{ github.ref }}
